### ISSUE TITLE
Error when installing Unity SDK and Core

### ISSUE THREAD

**Issue by jayateertha043** [watson-developer-cloud/unity-sdk#554]
I get error - "Assets\unity-sdk-core-0.1.0\unity-sdk-core-0.1.0\Connection\RESTConnector.cs(645,24): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
"
after I imported both unity-sdk and unity-sdk-core as mentioned.

**Comment by mediumTaj** [comment]
Have you gone into your build settings and set Scripting Runtime Version and Api Compatibility Level to .NET 4.x equivalent?
https://github.com/watson-developer-cloud/unity-sdk#configuring-unity

**Comment by jayateertha043** [comment]
Yes
It got fixed now
Thank you
Jayateertha G

On 2 Apr 2019 9:06 pm, "Ajiemar Santiago" <notifications@github.com> wrote:

Have you gone into your build settings and set Scripting Runtime Version
and Api Compatibility Level to .NET 4.x equivalent?
https://github.com/watson-developer-cloud/unity-sdk#configuring-unity

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/watson-developer-cloud/unity-sdk/issues/554#issuecomment-479055526>,
or mute the thread

**Comment by Holofrenia** [comment]
Hi,
I'm having some problems with Watson:
The type name 'Error' does not exist in the type 'RESTConnector'
This error appeared after I turned back to the  NEt 4.xEquivalent and .NET 4.x 
I'm working with Unity 2018.3.14f1
Thanks in advance.

**Comment by FLYINGSKATE** [comment]
> Hi,
> I'm having some problems with Watson:
> The type name 'Error' does not exist in the type 'RESTConnector'
> This error appeared after I turned back to the NEt 4.xEquivalent and .NET 4.x
> I'm working with Unity 2018.3.14f1
> Thanks in advance.

Paste this class before Form and after Response Class in RESTConnector.cs

/// <summary>
        /// Class to encapsulate an error returned from a server request.
        /// </summary>
        public class Error
        {
            /// <summary>
            /// The url that generated the error.
            /// </summary>
            public string URL { get; set; }
            /// <summary>
            /// The error code returned from the server.
            /// </summary>
            public long ErrorCode { get; set; }
            /// <summary>
            /// The error message returned from the server.
            /// </summary>
            public string ErrorMessage { get; set; }
            /// <summary>
            /// The contents of the response from the server.
            /// </summary>
            public string Response { get; set; }
            /// <summary>
            /// Dictionary of headers returned by the request.
            /// </summary>
            public Dictionary<string, string> ResponseHeaders { get; set; }

            public override string ToString()
            {
                return string.Format("URL: {0}, ErrorCode: {1}, Error: {2}, Response: {3}", URL, ErrorCode,
                                     string.IsNullOrEmpty(ErrorMessage) ? "" : ErrorMessage,
                                     string.IsNullOrEmpty(Response) ? "" : Response);
            }
        }
